name: Copy files from Repository to runner machine
on: [push]


jobs:
    copy-repo-object:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              run: |
                git init
                git remote add origin "https://GITHUB_ACTOR${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files
              run: ls -a