name: Print Working Dir & shells
on: [push]

jobs:
    display-inbuilt-dir-shells-obj:
        runs-on: ubuntu-latest
        steps:
            - name: Github names
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

