name: practicing running on dependent workflows
on: 
  push:
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]



jobs:
  workflow-one:
    runs-on: ubuntu-latest
    steps:
      - name: running one
        run: |
          echo: $GITHUB_SHA
          echo: $GITHUB_REF
      - uses: actions/checkout@v4


