name: setting error messages and warnings
on: [push]

jobs:
    setting-messages-object:
        runs-on: ubuntu-latest
        steps:
            - name: Setting and error message
              run: echo "::error::missing semicolon"
            - name: Setting error message with params"
              run: echo "::error title:Error Title, file=app.js, line = 2, endline=3, col=5, endcolumn=7::missing semicolon"
  
