name: Practicing actions
on: [push]


jobs:
  actions-objects:
    runs-on: ubuntu-latest
    steps: 
      - name: using action
        id: greet
        uses: action/hello-world-javascript-action@a5188c871c8bf440b511e0a76dd8e0bd8d3fe0b0
        with:
          who-to-greet: Amar
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time}}"
