name: js action for greeting
on: [push]

jobs: 
    object-greeting:
        runs-on: ubuntu-latest
        steps:
            - name: first step of using js
              id: greet
              uses: actions/hello-world-javascript-action@a5188c871c8bf440b511e0a76dd8e0bd8d3fe0b0
              with:
                who-to-greet: Amar
            - name: Log greeting Time
              run: echo "${{steps.greet.outputs.time}}"